apiVersion: v1
kind: Service
metadata:
  name: mercurybot-gt-bitcoinj
  labels:
    app: mercurybot-gt
spec:
  ports:
    - protocol: TCP
      port: 8000
  selector:
    app: mercurybot-gt
    tier: bitcoinj
  clusterIP: None

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mercurybot-gt-bitcoinj
  labels:
    app: mercurybot-gt
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mercurybot-gt
        tier: bitcoinj
    spec:
      containers:
      - image: 584051155560.dkr.ecr.eu-west-1.amazonaws.com/bitcoinj:latest
        name: bitcoinj
        env:
        - name: NETWORK
          value: PROD
        - name: EFSFOLDER
          value: /mnt/efs/gt
        ports:
        - containerPort: 8000
          name: bitcoinj
        livenessProbe:
          tcpSocket:
            port: 8000
          initialDelaySeconds: 600
          periodSeconds: 60
        volumeMounts:
        - name: bitcoinj-persistent-storage
          mountPath: /mnt/efs
      volumes:
      - name: bitcoinj-persistent-storage
        persistentVolumeClaim:
          claimName: efs
      nodeSelector:
        instance: gt