FROM python:2
RUN pip install tailon
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

RUN mkdir /tailon
ADD run_tailion.sh /tailon/run_tailion.sh
RUN chmod +x /tailon/run_tailion.sh

EXPOSE 8084
WORKDIR "/tailon"

CMD ["/tailon/run_tailion.sh"]
