apiVersion: v1
kind: Service
metadata:
  name: mercurybot-gt-telegram
  labels:
    app: mercurybot-gt
spec:
  selector:
    app: mercurybot-gt
    tier: telegram-bot
  clusterIP: None

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mercurybot-gt-telegram
  labels:
    app: mercurybot-gt
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mercurybot-gt
        tier: telegram-bot
    spec:
      containers:
      - image: 584051155560.dkr.ecr.eu-west-1.amazonaws.com/telegram_bot:latest
        name: telegram-bot
        env:
        - name: MERCURYBOT_HOST
          value: mercurybot-gt-bot
        - name: BITCOINJ_HOST
          value: mercurybot-gt-bitcoinj
        - name: MYSQL_HOST
          value: mercurybot-mysql
        - name: MYSQL_USER
          value: crypto
        - name: MYSQL_PASS
          value: '!@#!QAZ2wsx'
        - name: MYSQL_DB
          value: gt_crypto
        - name: EFSFOLDER
          value: /mnt/efs/gt
        - name: TEST_MODE
          value: 'False'
        volumeMounts:
        - name: telegram-bot-persistent-storage
          mountPath: /mnt/efs
      volumes:
      - name: telegram-bot-persistent-storage
        persistentVolumeClaim:
          claimName: efs
      nodeSelector:
        instance: gt